require("busted.runner")()
local test = require('velox.lua.test')
describe('test util', function()
    local new_test_get
    local new_test_post
    before_each(function()
        new_test_get = test.new("GET", "http:localhost:3000")
        new_test_post = test.new("POST", "http:localhost:3000")
    end)
    it('new', function()
        assert.same(new_test_get.method, "GET")
        assert.same(new_test_get.url, "http:localhost:3000")
        assert.is_nil(new_test_get._certificate)
        assert.is_nil(new_test_get._key)
        assert.is_nil(new_test_get._ca)
        assert.same(#new_test_get.headers, 0)
        assert.same(#new_test_get._headers, 0)
        assert.same(#new_test_get._asserts, 0)
    end)
    it('send', function()
       local body = '{"name":"Hello"}'
        new_test_get:send(body)
        assert.same(new_test_get._body.name, "Hello")
        body = 'hello'
        new_test_get:send(body)
        assert.same(new_test_get._body, '{"name":"Hello"}hello')
        new_test_get:send(4)
        assert.same(new_test_get._body, 4)
    end)
    it('set', function()
       local header = { ['Content-Type'] = 'application/json' }
        new_test_get:set(header)
        assert.same(new_test_get._headers['content-type'], 'application/json')
    end)
    it('cert', function()
       local cert = './cert.pem'
        new_test_get:cert(cert)
        assert.same(new_test_get._certificate, cert)
    end)
    it('key', function()
       local key = './key.pem'
        new_test_get:key(key)
        assert.same(new_test_get._key, key)
    end)
    it('ca', function()
        local ca = './ca.pem'
        new_test_get:ca(ca)
        assert.same(new_test_get._ca, ca)
    end)
end)